### PR TITLE
Add linter html

### PR DESCRIPTION
**Pull request by hsy822**
#14

It will check HTML when every time you commit code. 

### Usage
1. Install pre-commit 
    - https://pre-commit.com/#installation
2. Install the git hook script
    - https://pre-commit.com/#3-install-the-git-hook-scripts

### Reference
- https://github.com/Lucas-C/pre-commit-hooks-nodejs

### CODE REVIEW

**Comment by ConsenSys-Academy** [comment]
Hi there @hsy822 ! Thanks so much for undertaking this!

We like the idea of using Github actions, but we purposely structured the code in the HTML in the staggered way we did to increase readability for folks newer to HTML. Is there a way to incorporate the styling we used? 

cc @Robbiekruszynski 

I think you might also have to do a `git pull` on the repo to update it, we just did a small PR merge.

Thanks again for your submission!

**Comment by hsy822** [comment]
I just sent new PR. #25

**Comment by hsy822** [comment]
> Hi @hsy822 We did structure the code to increase readability for others. I will look into this though, appreciate your involvement in this!

Thanks @Robbiekruszynski, let me know your opinion and I'll try to adapt the code accordingly:)

**Comment by ConsenSys-Academy** [comment]
Hey there @hsy822 ! Apologies for the delay, could you close this PR in favor of #25?

**Pull request closed without merging**
