### PR TITLE
Delete all rel="noopener noreferrer" cases in .html

### PR DESCRIPTION
**Pull request by ssameghini**
Simply forked, cloned, edited, pushed and now requesting pulling.
On VSCode, in the root folder, I searched for all occurrences of 'rel="noopener noreferrer"' in the html files, and replaced them with a space, wich deletes them.
Hope that's just what you needed, it is my first contribution ever...

### CODE REVIEW

**Comment by jackm9367** [comment]
Hey @ssameghini - sorry! I accidentally stole your issue. 
I will mention this in the #16 issue chat.

**Comment by jackm9367** [comment]
In terms of the code changes, instead of replacing the `rel="noopener noreferrer"` occurrences with a space, I would replace them with just "" (as there is no real need for whitespace). 
A possible solution to this would be a find and replace for " >" and replace it with "". 
Any questions please let me know!
Cheers

**Comment by cooganb** [comment]
@ssameghini @jackm9367 thank you both for contributing and @ssameghini congratulations on your first PR! Do you think you'd be able to incorporate the changes @jackm9367 suggested? Happy to walk you through anything. 

Apologies for the delay in getting back, we were asleep when this happened!

**Comment by ssameghini** [comment]
Thanks @jackm9367 for the suggestion, it makes absolute sense. I'll have that changed and re-do the pull request.
It's no problem at all the authorship of the solution; I didn't know that it needed to be assigned first by requesting it. It's part of getting to know the ways of contributing.
And of course, @cooganb, I'll have those changes made. Thanks for the congratulations!

**Comment by ssameghini** [comment]
Well, I finally could remove all the whitespaces generated by the deletion of rel noopener noreferrer, including whitelines where that expression was written isolated from the rest of the <a> element.
I hope it does it!

**Comment by ConsenSys-Academy** [comment]
Congratulations on your first open-source contribution @ssameghini !! 

Curious, how did you find the repo?

**Comment by ssameghini** [comment]
Thanks, @ConsenSys-Academy !
I found the repo with this issue in [Good First Issues](https://goodfirstissues.com/), searching for potencial contributions that can help me practice.

**Comment by cooganb** [comment]
Awesome! If you're interested in the course itself its available here for
free:

https://courses.consensys.net/courses/bootcamp-basic-training

And congratulations on your first contribution to an open source project!

**Pull request merged**
