### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by dasapokhai**
Line 41; changed "lead to people to" to "cause people to"

### CODE REVIEW

**Comment by ConsenSys-Academy** [comment]
Hey @dasapokhai ! We super appreciate the effort to make a PR, but this is a subtle word-choice point, we're looking for catching errors / bugs or being able to make substantive changes that will improve the course dramatically.

That's our fault for not getting contributor guidelines together, but we will add them there.

Does that make sense? Again, very grateful for your effort.

**Comment by ConsenSys-Academy** [comment]
Happy to clarify more even though we closed the PR

**Comment by dasapokhai** [comment]
Yea please, thanks. Will bear that in mind as I go through the course. 
Regards

**Comment by ConsenSys-Academy** [comment]
Thanks for understanding!

**Pull request closed without merging**
