### PR TITLE
add git action for html linter & fix some tags

### PR DESCRIPTION
**Pull request by hsy822**
#14 

Added git action for HTML linter. (DO NOT need to install pre-commit.)

It is set to maintain the existing tag style as much as possible.

However, the /M3/L2/index.html L61: \<AGRUMENT\> part was partially modified to maintain the 'tag-pair' setting.

To modify the rules, use the .htmlhintrc file in .github/linters/  folder.
You can check more [options](https://htmlhint.com/docs/user-guide/list-rules) in here

### Reference
- https://github.com/github/super-linter

### CODE REVIEW

**Comment by ConsenSys-Academy** [comment]
Thanks so much for doing this, @hsy822 ! A few points of clarification:

1) This runs when a commit is pushed to Github?
2) Does the formatting happen on the committed changes, not locally?

It might also be good to split up the linter commit from the HTML changes into two separate PRs, is that possible?

**Comment by ConsenSys-Academy** [comment]
Is the `.DS_Store` file necessary?

**Review by ghost — CHANGES_REQUESTED** [review]
Hi there @hsy822 !

A few items: Do you need to include `.DS_Store` file?

It might make more sense to separate the implementation of the HTML linter using Github Actions (which is great!) with the HTML changes included here. I'm assuming the changes are from the linter, so we may need to merge the HTML changes as one commit, then the linter implementation as a second commit.

There also looks like there are some big diffs with some of the lessons, like `M1/L2/index.html`, those might be a mistake?

**Comment by ConsenSys-Academy** [comment]
Also, would it be possible to have the linter automatically remove `rel="noopener noreferrer"` from `<a href>` tags?

**Comment by hsy822** [comment]
> Is the [`.DS_Store` file](https://github.com/ConsenSys-Academy/basic-training/pull/25/files#diff-e2eb93a61ffd7877ea5c751abcb3a618e8e2e9a2073a27f66d4114fe10819f86) necessary?

No, It was my mistake:)

**Comment by hsy822** [comment]
> Thanks so much for doing this, @hsy822 ! A few points of clarification:
> 
> 1. This runs when a commit is pushed to Github?
> 2. Does the formatting happen on the committed changes, not locally?
> 
> It might also be good to split up the linter commit from the HTML changes into two separate PRs, is that possible?

1. Yes it does. This runs when a commit is pushed to Github.
2. The super-linter finds issues and reports them to the console output. Fixes are suggested in the console output but not automatically fixed, and a status check will show up as failed on the pull request. If you want to use it locally, you need to install docker([https://github.com/github/super-linter/blob/master/docs/run-linter-locally.md](https://github.com/github/super-linter/blob/master/docs/run-linter-locally.md)).

I will seperate PRs :)

**Comment by hsy822** [comment]
> Also, would it be possible to have the linter automatically remove `rel="noopener noreferrer"` from `<a href>` tags?

Unfortunately, Fixes are suggested in the console output but not automatically fixed.

**Comment by hsy822** [comment]
> Hi there @hsy822 !
> 
> A few items: Do you need to include `.DS_Store` file?
> 
> It might make more sense to separate the implementation of the HTML linter using Github Actions (which is great!) with the HTML changes included here. I'm assuming the changes are from the linter, so we may need to merge the HTML changes as one commit, then the linter implementation as a second commit.
> 
> There also looks like there are some big diffs with some of the lessons, like `M1/L2/index.html`, those might be a mistake?

**Comment by hsy822** [comment]
I will close this and make another PRs :)

**Pull request closed without merging**
